# Site
repository: sproogen/jameswgrant
favicon: images/favicon.ico

version: 2

# Personal info
name: Dario Stähelin
title: Research Associate & Ph.D. Student
email: dario.staehelin@gmail.com

# Social links
facebook_username: dario.staehelin
instagram_username: stahelinski
linkedin_username: dariostaehelin
orcid_username: 0000-0002-2467-5593
googlescholar_username: gRPqRAQAAAAJ

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  Hi, my name is Dario Stähelin, I’m a fourth-year Ph.D. student in Information Systems at the University of Zurich. I am currently working on my dissertation studying the empowering effect of digital technology in healthcare. 

  I am passionate about digital innovations that address relevant user needs and preferences and contribute to a better future for individuals and society. I strive in ambiguous and interdisciplinary environments, where I can bridge boundaries between stakeholders and collaboratively find a mutual solution. New technologies always fascinate me as I am eager to explore their utility for individuals and businesses. 

content:
  - title: Projects # Title for the section
    layout: list
    content:
      - layout: top-middle
        border: weak
        title: Digital Companion
        link: [webiste] (https://www.ifi.uzh.ch/en/imrg/research/Patient-and-Data-centered-Healthcare/Digital-Companion.html)
        additional_links:
          - title: sproogen/modern-resume-theme
            icon: fab fa-github
            url: https://github.com/sproogen/modern-resume-theme
        quote: >
          A modern simple static resume template and theme. Powered by Jekyll and GitHub pages.
        description: |
          This is a <mark>Jekyll</mark> theme that I have recently created, in fact it is what this resume has been built with.
          I decided I wanted to learn how to create a fully open source project and thought that this would be the perfect project to do this with.
          It has allowed me to share something I have created in a way that will be helpful for lots of people while also learning from this myself.
      - layout: top-middle
        title: itsgoingto.be
        link: www.itsgoingto.be
        additional_links:
          - title: sproogen/itsgoingto.be
            icon: fab fa-github
            url: https://github.com/sproogen/itsgoingto.be
        quote: >
          itsgoingto.be is a simple voting site where a user can ask a question or topic top put to a vote. This question
          can then be shared with their friends/colleagues to vote on things like 'Where should we go for lunch?'.
        description: |
          The API for this site has been build using <mark>Node.js</mark> while the front end is a <mark>React</mark>/<mark>Redux</mark> app.
          I have used <mark>Docker</mark> to set up a development environment and <mark>Heroku</mark> to deploy and host the site. I have
          a suite of unit and API tests for the backend and unit tests for the front end.

          I have been using this project as a way to increase many of my skills and also learn new things, most recently sockets and Node.JS. I have particually
          enjoyed managing my own project and designing my own architecture and implementing this to a high standard.

          Feel free to check out the whole project on GitHub to get a feel for how I work [here](https://github.com/sproogen/itsgoingto.be).

  - title: Experience
    layout: list
    content:
      - layout: left
        border: weak
        title: University of Zurich
        sub_title: Research Associate & Ph.D. Student
        caption: October 2019 - present
        link: https://www.ifi.uzh.ch/en/imrg.html
        description: | # this will include new lines to allow paragraphs
          Led the exploration phase of an innovation project to identify opportunities for integrating conversational agents in financial advisory services
          
          Collaborated on ComBaCaL, a digital health project, to empower community health workers to provide non-communicable disease care in Lesotho
          
          Led the scientific evaluation of the Digital Companion, a closed-loop digital health system for chronic disease care in Switzerland
          
          Supervised over 20 students in theses and project works on digital health and augmented reality topics

      - layout: left
        border: weak 
        title: University of St. Gallen
        sub_title: Research Associate & Ph.D. Student
        caption: February 2019 - September 2019
        link: https://item.unisg.ch/en
        description: | # this will include new lines to allow paragraphs
          Conducted a research project on value-based marketing in industrial services such as predictive and augmented reality-supported maintenance
          
          Supported the “Smart MedTech” benchmarking project studying the effects of digitization in the MedTech industry
          
          Acquisition of funds for the research project “Novel Digital Services for Highly Dynamic Manufacturing Machines”

      - layout: left
        border: weak 
        title: KPMG Switzerland
        sub_title: Consultant Digital Transformation
        caption: February 2017 - November 2018
        link: https://kpmg.com/ch/de/home.html
        quote: >
          80%, besides studies
        description: | # this will include new lines to allow paragraphs
          Worked as a consultant and business analyst and project lead for a major Swiss Bank in various digital transformation projects strongly linked to customer experience
          
          Consulted a cantonal bank in developing a digital transformation roadmap
          
          Co-developed an Industry 4.0 offering within the Digital Transformation Unit to support clients regarding the configuration and improvement of their value chain

      - layout: left
        border: weak 
        title: UBS AG
        sub_title: Securities Specialist
        caption: February 2015 - December 2016
        link: https://www.ubs.com/ch/de.html
        quote: >
          80%, besides studies
        description: | # this will include new lines to allow paragraphs
          Led a task force project within the bilateral tax regulation between Switzerland and Austria/UK 
          
          SME and group lead for policy-specific subjects, including account closing and cash remittances 

      - layout: left
        border: weak 
        title: UBS AG
        sub_title: Securities Specialist
        caption: August 2013 - February 2015
        link: https://www.ubs.com/ch/de.html
        quote: >
          40-50%, besides studies
        description: | # this will include new lines to allow paragraphs
          Led a process optimization project in the French tax regulation department
          
          Assisted the management in administrative tasks associated with project coordination and planning (e.g., risk reporting, deliverables presentation, and resource allocation)

  - title: Education
    layout: list
    content:
      - title: University of Zurich
        sub_title: Doctoral Program Information Systems
        caption: Since 2019
        description: |
          text
          
      - title: University of St. Gallen
        sub_title: Master’s in Business Innovation - Average Grade 5.29
        caption: 2016 - 2018
        description: |
          During my Master's degree at the University of St. Gallen I could build on my previous studies and advance my skills and interest in digital transformation and its effect on individuals, businesses, and society. My course work comprised: LIST

      - title: University of St. Gallen
        sub_title: Bachelor’s in Business Administration - Average Grade 4.92
        caption: 2012 - 2016
        description: |
          During my Bachelor's degree at the University of St. Gallen I laid a broad foundation in business, economics, and law.

  - title: When I'm Not At Work
    layout: text
    content: | # this will include new lines to allow paragraphs
      When I'm not sitting at my desk, I try to spend as much time as possible outdoors. Since I quit American Football, I picked up running again and I enjoy weight lifting. As a Swiss, I love hiking in the Alps or anywhere else. If I'm not out and about, I enjoy gardening in our little backyard.  

      I'm also a photography enthusiast, specifically wildlife photography and the occasional portrait and landscape. You can find some of my work on Instagram - [the_naturejourney](https://www.instagram.com/the_naturejourney/).

      Finally, I love food. So, cooking and most importantly eating are amongst my favorite non-sportive activities besides reading a well-written Fantasy or Sci-Fi Book.

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
