# Site
repository: sproogen/jameswgrant
favicon: images/favicon.ico

version: 2

# Personal info
name: Dario Stähelin
title: Research Associate & Ph.D. Student
email: dario.staehelin@gmail.com

# Social links
facebook_username: dario.staehelin
instagram_username: stahelinski
linkedin_username: dariostaehelin
orcid_username: 0000-0002-2467-5593
googlescholar_username: gRPqRAQAAAAJ

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  Hi, my name is Dario Stähelin, I’m a fourth-year Ph.D. student in Information Systems at the University of Zurich. I am currently working on my dissertation studying the empowering effect of digital technology in healthcare. 

  I am passionate about digital innovations that address relevant user needs and preferences and contribute to a better future for individuals and society. I strive in ambiguous and interdisciplinary environments, where I can bridge boundaries between stakeholders and collaboratively find a mutual solution. New technologies always fascinate me as I am eager to explore their utility for individuals and businesses. 

content:
  - title: Recent Projects # Title for the section
    layout: list
    content:
      - layout: top-middle
        border: weak
        title: Digital Companion
        link: https://www.ifi.uzh.ch/en/imrg/research/Patient-and-Data-centered-Healthcare/Digital-Companion.html
        quote: >
          Closing the loop in chronic care with digital health. 
        description: |
          Together with ZHAW, Helmedica, and the Cobedias Institute, I worked on the Digital Companion project. The Digital Companion aims to "close the loop" for patients between consultations with medical professionals in chronic disease. Through an integrated and continuous care approach, the Digital Companion addresses the fragmentation of care. 
        
          Patients and medical professionals share information such as patient-generated health data (e.g., food and activity diaries) and patient history to improve patient-provider collaboration for patient-centered care. In my role, I contributed to the design of the software prototype as a subject matter expert and led the scientific evaluation in Winter/Spring 2023. 
          
          During this project, I was able to expand my experience in user- and product-centered design as well as qualitative analysis methods. In this project, I was fascinated by the enormous effect that the connection with medical professionals through the app had on patients.
          
      - layout: top-middle
        title: ComBaCaL
        link: https://www.ifi.uzh.ch/en/imrg/research/Patient-and-Data-centered-Healthcare/Community-Based-chronic-disease-Care-Lesotho.html
        quote: >
          Tackling the NCD epidemic in Lesotho by digitally empowering community health workers to provide NCD care at the community level.
        description: |
          ComBaCaL is a digital health implementation project for community-based NCD care in Lesotho together with SwissTPH, SolidarMed, and the National University Lesotho.ComBaCaL aims to tackle the rapidly spreading NCD epidemic in Lesotho by capacitating community health workers (CHWs) with a digital health tool to provide NCD care at the community level. 
          
          The CHWs in ComBaCaL screen and monitor NCDs, specifically type 2 diabetes and hypertension, guided through clinical algorithms instantiated in a digital health app on a tablet. In addition to screening and monitoring services, they provide a care package including prescribing first-line treatment for uncomplicated type 2 diabetes. This way, ComBaCaL aims to provide uncomplicated type 2 diabetes care in the community, reducing the need for travel and making care more accessible for people in remote areas without compromising patient safety and quality of care. 
          
          In my role, I was the key driver for problem and solution exploration, requirements engineering, and product development. In the project, I gained additional experience in coordinating interdisciplinary, multicultural, and geographically dispersed teams. ComBaCaL is a perfect example of projects I am passionate about. I am driven by the positive impact of technology on individuals and society as well as the interdisciplinary collaboration.  


      - layout: top-middle
        title: Heinzelmännli
        link: https://www.ifi.uzh.ch/en/imrg/research/advisory-service-support/heinzelmaennli.html
        quote: >
          A collaborative digital agent for immersive financial advisory services
        description: |
          Heinzelmännli is a research project in close collaboration with Innofactory, recapp IT, Ergon Informatics, and the University of Applied Sciences and Arts Northwestern Switzerland. The aim of Heinzelmännli is to integrate digital agents into financial advisory services.

          Building on a previous research project on augmented reality systems for financial advisory services, Heinzelmännli explored the potential of digital agents to provide a more immersive and holistic service experience. The digital agent reduces the cognitive burden on advisors by automatically documenting and summarizing service encounters. Further, it provides suggestions for potential investments based on the conversation flow or retrieves additional information for clients and advisors such as financial reports on a specific company. 
          
          In the Heinzelmännli project, I led the exploration phase to identify opportunities for integrating digital agents in the augmented reality system. In this role, I coordinated six project partners (two banks, two technology partners, and two research institutions) to develop a product vision and strategic roadmap in accordance with innovation and research aims.


  - title: Experience
    layout: list
    content:
      - layout: left
        border: weak
        title: University of Zurich
        sub_title: Research Associate & Ph.D. Student
        caption: October 2019 - present
        link: https://www.ifi.uzh.ch/en/imrg.html
        description: | # this will include new lines to allow paragraphs
          Led the exploration phase of an innovation project to identify opportunities for integrating conversational agents in financial advisory services
          
          Collaborated on ComBaCaL, a digital health project, to empower community health workers to provide non-communicable disease care in Lesotho
          
          Led the scientific evaluation of the Digital Companion, a closed-loop digital health system for chronic disease care in Switzerland
          
          Supervised over 20 students in theses and project works on digital health and augmented reality topics

      - layout: left
        border: weak 
        title: University of St. Gallen
        sub_title: Research Associate & Ph.D. Student
        caption: February 2019 - September 2019
        link: https://item.unisg.ch/en
        description: | # this will include new lines to allow paragraphs
          Conducted a research project on value-based marketing in industrial services such as predictive and augmented reality-supported maintenance
          
          Supported the “Smart MedTech” benchmarking project studying the effects of digitization in the MedTech industry
          
          Acquisition of funds for the research project “Novel Digital Services for Highly Dynamic Manufacturing Machines”

      - layout: left
        border: weak 
        title: KPMG Switzerland
        sub_title: Consultant Digital Transformation
        caption: February 2017 - November 2018
        link: https://kpmg.com/ch/de/home.html
        quote: >
          80%, besides studies
        description: | # this will include new lines to allow paragraphs
          Worked as a consultant and business analyst and project lead for a major Swiss Bank in various digital transformation projects strongly linked to customer experience
          
          Consulted a cantonal bank in developing a digital transformation roadmap
          
          Co-developed an Industry 4.0 offering within the Digital Transformation Unit to support clients regarding the configuration and improvement of their value chain

      - layout: left
        border: weak 
        title: UBS AG
        sub_title: Securities Specialist
        caption: February 2015 - December 2016
        link: https://www.ubs.com/ch/de.html
        quote: >
          80%, besides studies
        description: | # this will include new lines to allow paragraphs
          Led a task force project within the bilateral tax regulation between Switzerland and Austria/UK 
          
          SME and group lead for policy-specific subjects, including account closing and cash remittances 

      - layout: left
        border: weak 
        title: UBS AG
        sub_title: Securities Specialist
        caption: August 2013 - February 2015
        link: https://www.ubs.com/ch/de.html
        quote: >
          40-50%, besides studies
        description: | # this will include new lines to allow paragraphs
          Led a process optimization project in the French tax regulation department
          
          Assisted the management in administrative tasks associated with project coordination and planning (e.g., risk reporting, deliverables presentation, and resource allocation)

  - title: Education
    layout: list
    content:
      - title: University of Zurich
        sub_title: Doctoral Program Information Systems
        caption: Since 2019
        description: |
          text
          
      - title: University of St. Gallen
        sub_title: Master’s in Business Innovation - Average Grade 5.29
        caption: 2016 - 2018
        description: |
          During my Master's degree at the University of St. Gallen I could build on my previous studies and advance my skills and interest in digital transformation and its effect on individuals, businesses, and society. My course work comprised:
          - Business Engineering - Digital Business & Transformation (Grade: 5)
          - Technology Entrepreneurship (Grade: 5)
          - Business Model Development (Grade: 5.5)
          - Digital Customer Interaction (Grade: 5.5)
          - Digital Nudging (Grade: 6)
          - Business Model Innovation (Grade: 5.5)
          - Industry 4.0 and Digital Value Creation (Grade: 5)
          - Industry 4.0: Smart Technologies in Operations Management (Grade: 5.5)
          - Successful Management of the Digital Transformation (Grade: 5.5)

          In my Master's thesis, I studied behavior change in long-term wearable users applying narrative interviews to elicit users' journeys with their wearable device (Grade: 5)


      - title: University of St. Gallen
        sub_title: Bachelor’s in Business Administration - Average Grade 4.92
        caption: 2012 - 2016
        description: |
          During my Bachelor's degree at the University of St. Gallen I laid a broad foundation in business, economics, and law. Further, I could already gain insights and experience in digitalization and entrepreneurship in courses such as: 
          - Internet and Social Media Start-ups (Grade 5.5)
          - Management in the Digital Economy - Enterprise 2.0 and Business 2.0 (Grade: 5.5)
          - Corporate Entrepreneurship (Grade: 5.5)
          - Service Management (Grade: 5)
          - Communication Psychology in Practice (Grade: 6)
          - Corporate Responsibility and Food Security (Grade: 5)

          I wrote my Bachelor's thesis on Digitalization in Swiss Banks, where I studied the maturity of Swiss banks in their digitalization progress through quantitative and qualitative methods (Grade: 5.25)

  - title: When I'm Not At Work
    layout: text
    content: | # this will include new lines to allow paragraphs
      When I'm not sitting at my desk, I try to spend as much time as possible outdoors. Since I quit American Football, I picked up running again and I enjoy weight lifting. As a Swiss, I love hiking in the Alps or anywhere else. If I'm not out and about, I enjoy gardening in our little backyard.  

      I'm also a photography enthusiast, specifically wildlife photography and the occasional portrait and landscape. You can find some of my work on Instagram - [the_naturejourney](https://www.instagram.com/the_naturejourney/).

      Finally, I love food. So, cooking and most importantly eating are amongst my favorite non-sportive activities besides reading a well-written Fantasy or Sci-Fi Book.

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
